Update justfile

diff --git a/minecraft/servers/Freebuild/justfile b/minecraft/servers/Freebuild/justfile
--- a/minecraft/servers/Freebuild/justfile
+++ b/minecraft/servers/Freebuild/justfile
@@ -39,13 +39,13 @@ copy-shared-plugins-folder:
 # Replace fields from the DiscordSRV config with values from .config/.env-minecraft
 fix-discordsrv-config:
     if server_type == "paper"; then
-	    sed -i "s/BotToken: \".*/BotToken: \"${discordsrv_token}\"/" ./plugins/DiscordSRV/config.yml
-	    sed -i "s/Channels: {\"global\": \".*/Channels: {\"global\": \"${discordsrv_channel}\"}/" ./plugins/DiscordSRV/config.yml
-	    sed -i "s/DiscordConsoleChannelId: \".*/DiscordConsoleChannelId: \"${discordsrv_console}\"/" ./plugins/DiscordSRV/config.yml
-	    sed -i "s@DiscordInviteLink: \".*@DiscordInviteLink: \"${discordsrv_inite}\"@" ./plugins/DiscordSRV/config.yml
+        sed -i "s/BotToken: \".*/BotToken: \"${discordsrv_token}\"/" ./plugins/DiscordSRV/config.yml
+        sed -i "s/Channels: {\"global\": \".*/Channels: {\"global\": \"${discordsrv_channel}\"}/" ./plugins/DiscordSRV/config.yml
+        sed -i "s/DiscordConsoleChannelId: \".*/DiscordConsoleChannelId: \"${discordsrv_console}\"/" ./plugins/DiscordSRV/config.yml
+        sed -i "s@DiscordInviteLink: \".*@DiscordInviteLink: \"${discordsrv_inite}\"@" ./plugins/DiscordSRV/config.yml
     else
-	    {{wrong_server_type()}}
-	    @exit 1
+        {{wrong_server_type()}}
+        @exit 1
     fi
 
 # Remove session.lock files from the worlds (in case of failed server shutdown)
@@ -57,13 +57,13 @@ prepare: copy-shared-paper-jar copy-shared-plugins-folder fix-discordsrv-config 
 # Perform a backup of the Minecraft server based on backuplist.txt. Optional parameter: SILENT=true/false
 backup:
 	screen -S minecraft-backup-${server_name} -d -m \
-		bash ${FREDDITCORE_DIR}/scripts/backup.sh ${FREDDITCORE_DIR}/minecraft/servers/${server_name} ${FREDDITCORE_DIR}/minecraft/backups/${server_name} ${SILENT}
+        bash ${FREDDITCORE_DIR}/scripts/backup.sh ${FREDDITCORE_DIR}/minecraft/servers/${server_name} ${FREDDITCORE_DIR}/minecraft/backups/${server_name} ${SILENT}
 
 # Start the Minecraft server in a screen session.
 start:
 	screen -S ${screen_name} -d -m \
-		bash ./start.sh ${server_name} ${mem_min} ${mem_max} true
-		@echo "Starting ${server_name}"
+        bash ./start.sh ${server_name} ${mem_min} ${mem_max} true
+        @echo "Starting ${server_name}"
 
 # Stop the Minecraft server's screen session
 stop:
@@ -83,15 +83,26 @@ console:
 	screen -d -r ${screen_name}
 
 # Purge Coreprotect data older than 60 days (requires server to be online)
-purge-coreprotect-db:
-ifeq (${BEFORE},)
-	@echo "missing BEFORE parameter (e.g., 'BEFORE=60d make purge-coreprotect-db' to purge data older than 60 days)"
-	@exit 1
-endif
-ifeq (${server_type},paper)
-	screen -r ${screen_name} -X stuff \
-		"co purge t:${BEFORE}^M"
-else
-	${wrong_server_type}
-	@exit 1
-endif
+purge-coreprotect-db BEFORE:
+    if BEFORE == ""; then
+        @echo "missing BEFORE parameter (e.g., 'BEFORE=60d make purge-coreprotect-db' to purge data older than 60 days)"
+        @exit 1
+    fi
+    if server_type == "paper"; then
+        screen -r {{screen_name}} -X stuff \
+            "co purge t:{{BEFORE}}^M"
+    else
+        {{wrong_server_type()}}
+        @exit 1
+    fi
+# ifeq (${BEFORE},)
+# 	@echo "missing BEFORE parameter (e.g., 'BEFORE=60d make purge-coreprotect-db' to purge data older than 60 days)"
+# 	@exit 1
+# endif
+# ifeq (${server_type},paper)
+# 	screen -r ${screen_name} -X stuff \
+# 		"co purge t:${BEFORE}^M"
+# else
+# 	${wrong_server_type}
+# 	@exit 1
+# endif
